languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Morethan 小站"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.svg"
  secondaryLogo = "img/logo_light.svg"
  description = "一个存放思考、感悟的网站"

[params.author]
  name = "Morethan"
  image = "img/figure.png"
  headline = "计算机、物理与AI理工男"
  bio = "计算机、物理与AI理工男"
  links = [
    { github = "https://github.com/morethan987" },
    { knowledgebase = "https://morethan987.github.io/KnowledgeBase"},
  ]