languageCode = "en"
languageName = "English"
weight = 1
title = "More's awesome website"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Morethan"
  email = "morthan@qq.com"
  image = "img/logo_transparent.png"
  headline = "A website for thinking and feeling."
  bio = "A website for thinking and feeling."
  links = [
    { github = "https://github.com/morethan987" },
  ]