disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "More's awesome website"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.svg"
  secondaryLogo = "img/logo_light.svg"
  description = "A website for thinking and feeling."
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Morethan"
  email = "morthan@qq.com"
  image = "img/figure.png"
  imageQuality = 96
  headline = "Computer, Physic & AI"
  bio = "Computer, Physic & AI"
  links = [
    { github = "https://github.com/morethan987" },
    { knowledgebase = "https://morethan987.github.io/KnowledgeBase"},
  ]