languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Morethan 小站"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "一个存放思考、感悟的网站"

[params.author]
  name = "Morethan"
  image = "img/logo_transparent.png"
  headline = "一个存放思考、感悟的网站"
  bio = "一个存放思考、感悟的网站"
  links = [
    { github = "https://github.com/morethan987" },
  ]